### ISSUE TITLE
MtlReader wrong parses at least map_Kd tag

### ISSUE THREAD

**Issue by dementia2029** [javagl/Obj#12]
Version 0.3.0, class `MtlReader`, line 160-161:
```
String mapKd = line.substring("map_Kd".length()).trim();
currentMtl.setMapKd(mapKd);
```
If line is ` "\tmap_Kd wood.jpg"`, we will get mapKd String value as a `"d wood.jpg"`.
We must also cut `"d "`

**Comment by javagl** [comment]
Thanks for reporting this. But this was already fixed via the PR https://github.com/javagl/Obj/pull/6 . It will be part of the next release.

OK to close?

**Comment by dementia2029** [comment]
Hi! Sure, you can close this issue. Thank you.
