### ISSUE TITLE
Propose: support physically-based rendering parameters in de.javagl.obj.Mtl

### ISSUE THREAD

**Issue by quminghaonanya** [javagl/Obj#22]
In 0.3.0 supported mtl attributes are:
Ka - Ambient component
Ks - Specular component
Kd - Diffuse component
map_Kd - Diffuse map
Ns - Shininess
D - Opacity

can we introduce more support to mtl attribute, such as pbr attributes:
Pr/map_Pr     # roughness
Pm/map_Pm     # metallic
Ps/map_Ps     # sheen
Pc            # clearcoat thickness
Pcr           # clearcoat roughness
Ke/map_Ke     # emissive
aniso         # anisotropy
anisor        # anisotropy rotation
norm          # normal map (RGB components represent XYZ components of the surface normal)

btw, I'ved add these attribute locally since I was developing a ar demo, and I'm willing to share my solution and create a mr, if possible.
is there any coverage standard or requirement if I want to contribute my solution.
Thanks

**Comment by javagl** [comment]
Supporting additional material properties is something that I would definitely consider. 

The point is: Which ones?

As a matter for fact, about 99.9% of all OBJ files use (no MTL at all or) a very simple MTL that just defines the diffuse color or texture. What _exactly_ is supposed to be supported in MTL is hard to know. The thing that comes closest to a "specification" is http://paulbourke.net/dataformats/mtl/ . (There's a similar specification for OBJ at http://paulbourke.net/dataformats/obj/ - did you know that OBJ supports various forms of B-spline-patches? No? Well, neither do 99.9% of the people who regularly work with OBJ...)

The given MTL specification _does_ go beyond what is commonly used in MTL files. And it goes beyond what is currently supported by this library. In fact, there is a branch at https://github.com/javagl/Obj/tree/materials where I extended the support for MTL, based on the specification. An example for a complex material (that, IIRC, was supposed to just contain "all available properties") can be found at https://github.com/javagl/Obj/commit/5bd204cb8d1a434897c7b3b786eb801cabff5832#diff-5436c761b7c9e2e3bd6f0d72fdb1331cda09fa9c9f4f36f4133961349290aba7 

Nothing of this resembles the properties that you suggested. So I have to ask: Where do the properties that you suggested come from? Is there a specification for that? (I know that they resemble the PBR material properties of glTF, which can be considered as the _de-facto standard_ for PBR definitions. But I have never seen that in the context of OBJ/MTL...)

**Comment by quminghaonanya** [comment]
Thansk for your professional and prompt reply.  
I got this idea simply beacuse blender exported a .mtl file which contains these PBR material properties and since this library doesn't contain these properties, I added some myself lol.
I must confess that I didn't refer any standard before proposed this, and know little about the .mtl specificaiton.
BTW, For blender, the feature of [extended .mtl with pbr property] was merged to the main branch and already released. though it is optional feature when export to the .mtl. 
here's the mr:https://projects.blender.org/blender/blender/commit/a99a62231e040a15c93add9ffa582ec9e1d9c4f1
and [Clara.io] exports the .mtl file along with these PBR material property as well.

**Comment by javagl** [comment]
The support does not seem to be sooo broad. They mention Clara.io, and the only "specification" that I could find is that in the linked blog post, which is also referred to by the Wikipedia article about MTL ad https://en.wikipedia.org/wiki/Wavefront_.obj_file#Physically-based_Rendering 

The blog post is old, but the structure that is proposed there seems to be similar (basically identical) to the information that can be represented with glTF, for example. The fact that Blender added an export option suggests that this may be/become some sort of "de-facto standard" as well, for the specific case of MTL. The properties seem to be purely defined as _additions_ to the existing properties in MTL. (And again: The current version of this library only has a subset of this, but the linked branch contains a few more). 

But... given all that, I'll put that task on my TODO list: I'll try to allocate some time for reviving the branch at https://github.com/javagl/Obj/tree/materials , and at least see whether/how the PBR parameters could sensibly be encoded there. (It's hard to give an exact timeline or make promises here, but ... maybe, after version 0.3.0 has been out for >5 years now, it's time for a version 0.4.0 ...)

**Comment by quminghaonanya** [comment]
Thank you for the detailed reply!
It has been a long time since the last release lol.
Must say It is a very useful and high-quality library, and here's my MR for support reading property from .mtl:https://github.com/javagl/Obj/pull/24/commits/7c0a0fd5c54dca0dbb2ca8fd4a8336161e219c91
which based on your [materials] branch. 
Currently it's WIP, and I'm not sure which attributes should be supported. so in this commit, I coded the overall structure, I think it is enough to demonstrate my idea.
I'm willing to contribute and do more if possible : ).
At the end, I think this proposal was answered perfectly! can close it as u wish.

**Comment by javagl** [comment]
I created a PR at https://github.com/javagl/Obj/pull/25 . 

I'd like to test this a bit more extensively. For example, with _real_ MTLs that have been exported from Clara.io or Blender. I might need some more time for that. If someone can provide some examples or perform tests, that could help.

If this is going to be part of a release, I'd update [`jgltf-obj`](https://github.com/javagl/JglTF/tree/master/jgltf-obj) to actually _use_ these values and create proper glTF assets with proper PBR materials. That would be something...

**Comment by javagl** [comment]
This was added via https://github.com/javagl/Obj/pull/25 and is part of version `0.4.0` that has just been released in Maven Central.
