### ISSUE TITLE
Invalid material names when leading white spaces are present

### ISSUE THREAD

**Issue by yperess** [javagl/Obj#5]
Found a small bug when a friend sent me a material file with the following:

```
  newmtl mat18
    Ka 0.00 0.00 0.00
    Kd 0.00 0.00 0.00
    map_Kd TextureFile.png
```

This resulted in a `DefaultMtl` object with name `tl_mat18` and mapKd `p_Kd TextureFile.png`

**Comment by javagl** [comment]
Thanks for pointing this out. I couldn't find any explicit statement in online "specs" about whether leading whitespaces are allowed or not, and had never encountered an OBJ/MTL with leading whitespaces before. But it should be trivial and safe to fix this my placing a `line = line.trim()` at the right spot in the `MtlReader`.

**Comment by yperess** [comment]
Yup, sorry, normally I'd do the work myself and send you a pull request but I'm swamped currently with a big deadline for tomorrow. I'll be happy to contribute in the future :)

**Comment by javagl** [comment]
Fixed via https://github.com/javagl/Obj/pull/6 , thanks @yperess !
